# -*- coding: utf-8 -*-
rubrics = [
	{'NUTS-1':'DE1','region':'Baden-Württemberg','rubric':'aprswx-dl-bw'},
	{'NUTS-1':'DE2','region':'Bayern','rubric':'aprswx-dl-by'},
	{'NUTS-1':'DE3','region':'Berlin','rubric':'aprswx-dl-be'},
	{'NUTS-1':'DE4','region':'Brandenburg','rubric':'aprswx-dl-bb'},
	{'NUTS-1':'DE5','region':'Bremen','rubric':'aprswx-dl-hb'},
	{'NUTS-1':'DE6','region':'Hamburg','rubric':'aprswx-dl-hh'},
	{'NUTS-1':'DE7','region':'Hessen','rubric':'aprswx-dl-he'},
	{'NUTS-1':'DE8','region':'Mecklenburg-Vorpomen','rubric':'aprswx-dl-mv'},
	{'NUTS-1':'DE9','region':'Niedersachsen','rubric':'aprswx-dl-ni'},
	{'NUTS-1':'DEA','region':'Nordrhein-Westfalen','rubric':'aprswx-dl-nw'},
	{'NUTS-1':'DEB','region':'Rheinland-Pfalz','rubric':'aprswx-dl-rp'},
	{'NUTS-1':'DEC','region':'Saarland','rubric':'aprswx-dl-sl'},
	{'NUTS-1':'DED','region':'Sachsen','rubric':'aprswx-dl-sn'},
	{'NUTS-1':'DEE','region':'Sachsen-Anhalt','rubric':'aprswx-dl-st'},
	{'NUTS-1':'DEF','region':'Schleswig-Holstein','rubric':'aprswx-dl-sh'},
	{'NUTS-1':'DEG','region':'Thüringen','rubric':'aprswx-dl-th'},
	{'NUTS-2':'CH01','region':'Genferseeregion','rubric':'aprswx-hb-01'},
	{'NUTS-2':'CH02','region':'Mittelland'     ,'rubric':'aprswx-hb-02'},
	{'NUTS-2':'CH03','region':'Nordwestschweiz','rubric':'aprswx-hb-03'},
	{'NUTS-2':'CH04','region':'Zuerich'        ,'rubric':'aprswx-hb-04'},
	{'NUTS-2':'CH05','region':'Ostschweiz'     ,'rubric':'aprswx-hb-05'},
	{'NUTS-2':'CH06','region':'Zentralschweiz' ,'rubric':'aprswx-hb-06'},
	{'NUTS-2':'CH07','region':'Tessin'         ,'rubric':'aprswx-hb-07'},

]
